# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewProject
  	pod 'IQKeyboardManagerSwift'      # 键盘管理
  	pod 'Alamofire'
  	pod 'CYLTabBarController'         # Tabbar框架
  	pod 'SwiftyJSON'                  # json解析
  	pod 'SnapKit'                     # 自动布局
  	pod 'SwiftyUserDefaults'
  	#pod 'SwiftProgressHUD'
    pod 'EFNavigationBar'
	pod 'ObjectMapper'
	pod 'Kingfisher'			      # 图片
end
